import 'package:easy_quiz_game/easy_quiz_game.dart';

final data = [
  QuizCategory(
    name: 'Birds',
    description: 'Quiz about Birds',
    iconImage: 'iconImage',
    difficulty: QuizDifficulty.beginner,
    quizzes: [
      Quiz(
        question: 'question',
        options: [
          'options',
          'options',
          'options',
          'options',
        ],
        correctIndex: 0,
        hint: 'hint',
        questionType: QuizQuestionType.image,
        difficulty: QuizDifficulty.beginner,
      ),
      Quiz(
        question: 'question',
        options: [
          'options',
          'options',
          'options',
          'options',
        ],
        correctIndex: 0,
        hint: 'hint',
        questionType: QuizQuestionType.text,
        difficulty: QuizDifficulty.beginner,
      ),
      Quiz(
        question: 'question',
        options: [
          'options',
          'options',
          'options',
          'options',
        ],
        correctIndex: 0,
        hint: 'hint',
        questionType: QuizQuestionType.text,
        difficulty: QuizDifficulty.beginner,
      ),
      Quiz(
        question: 'question',
        options: [
          'options',
          'options',
          'options',
          'options',
        ],
        correctIndex: 0,
        hint: 'hint',
        questionType: QuizQuestionType.text,
        difficulty: QuizDifficulty.beginner,
      ),
    ],
  ),
  QuizCategory(
    name: 'Birds',
    description: 'Quiz about Birds',
    iconImage: 'iconImage',
    difficulty: QuizDifficulty.beginner,
    quizzes: [
      Quiz(
        question: 'question',
        options: [
          'options',
          'options',
          'options',
          'options',
        ],
        correctIndex: 0,
        hint: 'hint',
        questionType: QuizQuestionType.image,
        difficulty: QuizDifficulty.beginner,
      ),
      Quiz(
        question: 'question',
        options: [
          'options',
          'options',
          'options',
          'options',
        ],
        correctIndex: 0,
        hint: 'hint',
        questionType: QuizQuestionType.text,
        difficulty: QuizDifficulty.beginner,
      ),
      Quiz(
        question: 'question',
        options: [
          'options',
          'options',
          'options',
          'options',
        ],
        correctIndex: 0,
        hint: 'hint',
        questionType: QuizQuestionType.text,
        difficulty: QuizDifficulty.beginner,
      ),
      Quiz(
        question: 'question',
        options: [
          'options',
          'options',
          'options',
          'options',
        ],
        correctIndex: 0,
        hint: 'hint',
        questionType: QuizQuestionType.text,
        difficulty: QuizDifficulty.beginner,
      ),
    ],
  ),
  QuizCategory(
    name: 'Birds',
    description: 'Quiz about Birds',
    iconImage: 'iconImage',
    difficulty: QuizDifficulty.beginner,
    quizzes: [
      Quiz(
        question: 'question',
        options: [
          'options',
          'options',
          'options',
          'options',
        ],
        correctIndex: 0,
        hint: 'hint',
        questionType: QuizQuestionType.image,
        difficulty: QuizDifficulty.beginner,
      ),
      Quiz(
        question: 'question',
        options: [
          'options',
          'options',
          'options',
          'options',
        ],
        correctIndex: 0,
        hint: 'hint',
        questionType: QuizQuestionType.text,
        difficulty: QuizDifficulty.beginner,
      ),
      Quiz(
        question: 'question',
        options: [
          'options',
          'options',
          'options',
          'options',
        ],
        correctIndex: 0,
        hint: 'hint',
        questionType: QuizQuestionType.text,
        difficulty: QuizDifficulty.beginner,
      ),
      Quiz(
        question: 'question',
        options: [
          'options',
          'options',
          'options',
          'options',
        ],
        correctIndex: 0,
        hint: 'hint',
        questionType: QuizQuestionType.text,
        difficulty: QuizDifficulty.beginner,
      ),
    ],
  ),
  QuizCategory(
    name: 'Birds',
    description: 'Quiz about Birds',
    iconImage: 'iconImage',
    difficulty: QuizDifficulty.beginner,
    quizzes: [
      Quiz(
        question: 'question',
        options: [
          'options',
          'options',
          'options',
          'options',
        ],
        correctIndex: 0,
        hint: 'hint',
        questionType: QuizQuestionType.image,
        difficulty: QuizDifficulty.beginner,
      ),
      Quiz(
        question: 'question',
        options: [
          'options',
          'options',
          'options',
          'options',
        ],
        correctIndex: 0,
        hint: 'hint',
        questionType: QuizQuestionType.text,
        difficulty: QuizDifficulty.beginner,
      ),
      Quiz(
        question: 'question',
        options: [
          'options',
          'options',
          'options',
          'options',
        ],
        correctIndex: 0,
        hint: 'hint',
        questionType: QuizQuestionType.text,
        difficulty: QuizDifficulty.beginner,
      ),
      Quiz(
        question: 'question',
        options: [
          'options',
          'options',
          'options',
          'options',
        ],
        correctIndex: 0,
        hint: 'hint',
        questionType: QuizQuestionType.text,
        difficulty: QuizDifficulty.beginner,
      ),
    ],
  ),
  QuizCategory(
    name: 'Birds',
    description: 'Quiz about Birds',
    iconImage: 'iconImage',
    difficulty: QuizDifficulty.beginner,
    quizzes: [
      Quiz(
        question: 'question',
        options: [
          'options',
          'options',
          'options',
          'options',
        ],
        correctIndex: 0,
        hint: 'hint',
        questionType: QuizQuestionType.image,
        difficulty: QuizDifficulty.beginner,
      ),
      Quiz(
        question: 'question',
        options: [
          'options',
          'options',
          'options',
          'options',
        ],
        correctIndex: 0,
        hint: 'hint',
        questionType: QuizQuestionType.text,
        difficulty: QuizDifficulty.beginner,
      ),
      Quiz(
        question: 'question',
        options: [
          'options',
          'options',
          'options',
          'options',
        ],
        correctIndex: 0,
        hint: 'hint',
        questionType: QuizQuestionType.text,
        difficulty: QuizDifficulty.beginner,
      ),
      Quiz(
        question: 'question',
        options: [
          'options',
          'options',
          'options',
          'options',
        ],
        correctIndex: 0,
        hint: 'hint',
        questionType: QuizQuestionType.text,
        difficulty: QuizDifficulty.beginner,
      ),
    ],
  ),
  QuizCategory(
    name: 'Birds',
    description: 'Quiz about Birds',
    iconImage: 'iconImage',
    difficulty: QuizDifficulty.beginner,
    quizzes: [
      Quiz(
        question: 'question',
        options: [
          'options',
          'options',
          'options',
          'options',
        ],
        correctIndex: 0,
        hint: 'hint',
        questionType: QuizQuestionType.image,
        difficulty: QuizDifficulty.beginner,
      ),
      Quiz(
        question: 'question',
        options: [
          'options',
          'options',
          'options',
          'options',
        ],
        correctIndex: 0,
        hint: 'hint',
        questionType: QuizQuestionType.text,
        difficulty: QuizDifficulty.beginner,
      ),
      Quiz(
        question: 'question',
        options: [
          'options',
          'options',
          'options',
          'options',
        ],
        correctIndex: 0,
        hint: 'hint',
        questionType: QuizQuestionType.text,
        difficulty: QuizDifficulty.beginner,
      ),
      Quiz(
        question: 'question',
        options: [
          'options',
          'options',
          'options',
          'options',
        ],
        correctIndex: 0,
        hint: 'hint',
        questionType: QuizQuestionType.text,
        difficulty: QuizDifficulty.beginner,
      ),
    ],
  ),
];
